version: '3.3'
services:
  amadeus-backend:
    container_name: amadeus-backend
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: xvblack/amadeus-backend
    environment:
      - TYPESENSE_ADDR=http://typesense:8108/
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_INDEX_NAME=${TYPESENSE_INDEX_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
      - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    entrypoint: ["/bin/sh", "-c", "PYTHONPATH=/app uv run app:app --host 0.0.0.0 --port 8000"]

  
  amadeus-backend-cron:
    container_name: amadeus-backend-cron
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: xvblack/amadeus-backend
    environment:
      - TYPESENSE_ADDR=http://typesense:8108/
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_INDEX_NAME=${TYPESENSE_INDEX_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
      - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    entrypoint: ["/bin/sh", "-c", "while true; do PYTHONPATH=/app uv run scripts/index_posts.py; sleep 30; done"]

  amadeus:
    container_name: amadeus
    restart: always
    depends_on:
      - typesense
    ports:
      - 8090:3000
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: runner
    image: xvblack/amadeus
    environment:
      - TYPESENSE_ADDR=http://typesense:8108/
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_INDEX_NAME=${TYPESENSE_INDEX_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
      - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
      - DEFAULT_PATH=/search
    networks:
      - default

  typesense:
    container_name: typesense
    restart: unless-stopped
    ports:
      - 8108:8108
    volumes:
      - 'typesense:/data'
    image: 'typesense/typesense:29.0.rc27'
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY}
    networks:
      - default

  # watchtower:
  #   container_name: watchtower
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - WATCHTOWER_LABEL_ENABLE=1
  #   command: --interval 30

volumes:
  typesense:

networks:
  default:
    name: amadeus_default