# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\xf2\x03\n\x04Seed\x12\x17\n\x06source\x18\x01 \x01(\x0e\x32\x07.Source\x12\n\n\x02id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x10\n\x08\x61\x62stract\x18\x04 \x01(\t\x12\x13\n\x0braw_content\x18\x05 \x01(\t\x12\x1d\n\x15\x66irst_touch_timestamp\x18\x06 \x01(\x03\x12$\n\rresource_type\x18\x07 \x01(\x0e\x32\r.ResourceType\x12!\n\x03web\x18\x08 \x01(\x0b\x32\x14.Seed.WebPagePayload\x12+\n\nattachment\x18\t \x01(\x0b\x32\x17.Seed.AttachmentPayload\x12+\n\x0epocket_payload\x18\x0b \x01(\x0b\x32\x13.Seed.PocketPayload\x1a$\n\x0eWebPagePayload\x12\x12\n\npublic_url\x18\x01 \x01(\t\x1a&\n\x11\x41ttachmentPayload\x12\x11\n\tfile_path\x18\x01 \x01(\t\x1a\x7f\n\rPocketPayload\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.Seed.PocketPayload.Status\"B\n\x06Status\x12\x14\n\x10UNDEFINED_STATUS\x10\x00\x12\x07\n\x03NEW\x10\x01\x12\x0c\n\x08\x41RCHIVED\x10\x02\x12\x0b\n\x07\x44\x45LETED\x10\x03\"\x91\x01\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\x12\x10\n\x08\x61\x62stract\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x08 \x01(\t\x12\x0c\n\x04html\x18\t \x01(\t\x12\x12\n\ntime_added\x18\x04 \x01(\x05\x12\x0c\n\x04tags\x18\x07 \x03(\t\x12\x0e\n\x06source\x18\x03 \x01(\t*a\n\x06Source\x12\x12\n\x0eUNDEFINED_SEED\x10\x00\x12\n\n\x06POCKET\x10\x01\x12\x0c\n\x08TELEGRAM\x10\x02\x12\x0f\n\x0bRSS_PODCAST\x10\x03\x12\n\n\x06\x46\x45\x45\x44LY\x10\x04\x12\x0c\n\x08INFERRED\x10\x05*V\n\x0cResourceType\x12\x1b\n\x17UNDEFINED_RESOURCE_TYPE\x10\x00\x12\x08\n\x04HTML\x10\x01\x12\x07\n\x03PDF\x10\x02\x12\x0b\n\x07PODCAST\x10\x03\x12\t\n\x05VIDEO\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOURCE._serialized_start=665
  _SOURCE._serialized_end=762
  _RESOURCETYPE._serialized_start=764
  _RESOURCETYPE._serialized_end=850
  _SEED._serialized_start=17
  _SEED._serialized_end=515
  _SEED_WEBPAGEPAYLOAD._serialized_start=310
  _SEED_WEBPAGEPAYLOAD._serialized_end=346
  _SEED_ATTACHMENTPAYLOAD._serialized_start=348
  _SEED_ATTACHMENTPAYLOAD._serialized_end=386
  _SEED_POCKETPAYLOAD._serialized_start=388
  _SEED_POCKETPAYLOAD._serialized_end=515
  _SEED_POCKETPAYLOAD_STATUS._serialized_start=449
  _SEED_POCKETPAYLOAD_STATUS._serialized_end=515
  _POST._serialized_start=518
  _POST._serialized_end=663
# @@protoc_insertion_point(module_scope)
