# POST http://192.168.31.181:8095/collections
POST http://localhost:8095/collections
Content-Type: application/json
X-TYPESENSE-API-KEY: xyz

{
  "name": "post-20230328",
  "fields": [
    {"name": "id", "type": "int32"},
    {"name": "url", "type": "string"},
    {"name": "time_added", "type": "int64"},
    {"name": "time_added_as_date", "type": "string", "optional": true},
    {"name": "source", "type": "string"},
    {"name": "tags", "type": "string[]", "facet": true},
    {"name": "title", "type": "string"},
    {"name": "abstract", "type": "string"},
    {"name": "content", "type": "string"},
    {"name": "html", "type": "string", "optional": true},
    {"name": ".*", "type": "auto"}
  ],
  "default_sorting_field": "time_added"
}