PATCH http://192.168.31.181:8108/collections/pocket-index
Content-Type: application/json
X-TYPESENSE-API-KEY: xyz
       
{
  "fields": [
    {
      "name": "html",
      "type": "string",
      "optional": true
    }
  ]
}
