PATCH http://localhost:8095/collections/{{$processEnv TYPESENSE_INDEX_NAME}}
Content-Type: application/json
X-TYPESENSE-API-KEY: {{$processEnv TYPESENSE_API_KEY}}
       
{
  "fields": [
    {
      "name": "html",
      "type": "string",
      "optional": true
    }
  ]
}
