version: '3.3'
services:
  amadeus:
    container_name: amadeus
    restart: always
    ports:
      - 8090:3000
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    image: xvblack/amadeus
    environment:
      - TYPESENSE_ADDR=http://typesense:8108/
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_INDEX_NAME=${TYPESENSE_INDEX_NAME}
      - REDIS_SERVER=redis://gpt-cache:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
      - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
      - AMADEUS_POSTGRES_DATABASE_URL=postgres://postgres:${AMADEUS_POSTGRES_DATABASE_PASSWORD}@postgres:5432/amadeus
    networks:
      - default
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${AMADEUS_POSTGRES_DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    ports:
      - "8091:5432"
    networks:
      - default
  gpt-cache:
    container_name: gpt-cache
    image: redis:latest
    ports:
      - "8093:6379"
    restart: unless-stopped
    networks:
      - default
  typesense:
    container_name: typesense
    restart: unless-stopped
    ports:
      - 8095:8108
    volumes:
      - 'typesense:/data'
    image: 'typesense/typesense:0.23.1'
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY}
    networks:
      - default

volumes:
  typesense:
  postgres-data:

networks:
  default:
    name: amadeus_default