version: '3.3'
services:
  amadeus:
    container_name: amadeus
    restart: always
    depends_on:
      - postgres
      - redis
      - typesense
      - qdrant
    ports:
      - 8090:3000
    build:
      context: ../frontend/
      dockerfile: Dockerfile
      target: runner
    image: xvblack/amadeus
    environment:
      - TYPESENSE_ADDR=http://typesense:8108/
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_INDEX_NAME=${TYPESENSE_INDEX_NAME}
      - REDIS_SERVER=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
      - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
      - AMADEUS_POSTGRES_DATABASE_URL=postgres://postgres:${AMADEUS_POSTGRES_DATABASE_PASSWORD}@postgres:5432/amadeus
      - DEFAULT_PATH=/search
    networks:
      - default
  amadeus-toolkit:
    container_name: amadeus-toolkit
    build:
      context: ../frontend/
      dockerfile: Dockerfile
      target: toolkit
    image: xvblack/amadeus-toolkit
    environment:
      - TYPESENSE_ADDR=http://typesense:8108/
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_INDEX_NAME=${TYPESENSE_INDEX_NAME}
      - REDIS_SERVER=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
      - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
      - AMADEUS_POSTGRES_DATABASE_URL=postgres://postgres:${AMADEUS_POSTGRES_DATABASE_PASSWORD}@postgres:5432/amadeus
    networks:
      - default
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${AMADEUS_POSTGRES_DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/pgdata'
    ports:
      - "8091:5432"
    networks:
      - default
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "8093:6379"
    restart: unless-stopped
    networks:
      - default
  typesense:
    container_name: typesense
    restart: unless-stopped
    ports:
      - 8095:8108
    volumes:
      - 'typesense:/data'
    image: 'typesense/typesense:0.23.1'
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY}
    networks:
      - default
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.0.3
    ports:
      - 8096:6333
      - 8097:6334

volumes:
  typesense:
  postgres-data:

networks:
  default:
    name: amadeus_default